/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockErc20Sol from "./MockERC20.sol";
export type { mockErc20Sol };
import type * as swapSol from "./swap.sol";
export type { swapSol };
